spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogProjectDb
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formatSql: true
  application:
    name: blog-backend
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

